package service

import "git.com/gol/model"

type RegionService interface {
	GetListOfRegions() []model.Region
	GetEmojiForCountry(country string) string
}

type regionService struct {
	regions []model.Region
}

func (regionService regionService) GetListOfRegions() []model.Region {
	return regionService.regions
}

func (regionService regionService) GetEmojiForCountry(country string) string {
	for _, region := range regionService.GetListOfRegions() {
		if region.CountryCode == country {
			return region.Flag
		}
	}
	return ""
}

func New() RegionService {
	return regionService{
		regions: []model.Region{
			{Key: "Australia", Location: "Australia", CountryCode: "AU", Flag: "🇦🇺"},
			{Key: "Canada", Location: "Canada", CountryCode: "CA", Flag: "🇨🇦"},
			{Key: "UK", Location: "UK", CountryCode: "UK", Flag: "🇬🇧"},
			{Key: "USA", Location: "USA", CountryCode: "US", Flag: "🇺🇸"},
			{Key: "China", Location: "China", CountryCode: "CN", Flag: "🇨🇳"},
			{Key: "Chile", Location: "Chile", CountryCode: "CL", Flag: "🇨🇱"},
			{Key: "New-Zealand", Location: "New Zealand", CountryCode: "NZ", Flag: "🇳🇿"},
			{Key: "Spain", Location: "Spain", CountryCode: "ES", Flag: "🇪🇸"},
			{Key: "Italy", Location: "Italy", CountryCode: "IT", Flag: "🇮🇹"},
			{Key: "Bahamas", Location: "Bahamas", CountryCode: "BS", Flag: "🇧🇸"},
			{Key: "Barbados", Location: "Barbados", CountryCode: "BB", Flag: "🇧🇧"},
			{Key: "Brazil", Location: "Brazil", CountryCode: "BR", Flag: "🇧🇷"},
			{Key: "Belgium", Location: "Belgium", CountryCode: "BE", Flag: "🇧🇪"},
			{Key: "France", Location: "France", CountryCode: "FR", Flag: "🇫🇷"},
			{Key: "Poland", Location: "Poland", CountryCode: "PL", Flag: "🇵🇱"},
			{Key: "Peru", Location: "Peru", CountryCode: "PE", Flag: "🇵🇪"},
			{Key: "Russia", Location: "Russia", CountryCode: "RU", Flag: "🇷🇺"},
			{Key: "Germany", Location: "Germany", CountryCode: "DE", Flag: "🇩🇪"},
			{Key: "Iran", Location: "Iran", CountryCode: "IR", Flag: "🇮🇷"},
			{Key: "India", Location: "India", CountryCode: "IN", Flag: "🇮🇳"},
			{Key: "Mexico", Location: "Mexico", CountryCode: "MX", Flag: "🇲🇽"},
			{Key: "Turkey", Location: "Turkey", CountryCode: "TR", Flag: "🇹🇷"},
			{Key: "Saudi-Arabia", Location: "Saudi Arabia", CountryCode: "SA", Flag: "🇸🇦"},
			{Key: "Antarctica", Location: "Antarctica", CountryCode: "AQ", Flag: "🇦🇶"},
			{Key: "Afghanistan", Location: "Afghanistan", CountryCode: "AF", Flag: "🇦🇫"},
			{Key: "Åland-Islands", Location: "Åland Islands", CountryCode: "AX", Flag: "🇦🇽"},
			{Key: "Albania", Location: "Albania", CountryCode: "AL", Flag: "🇦🇱"},
			{Key: "Algeria", Location: "Algeria", CountryCode: "DZ", Flag: "🇩🇿"},
			{Key: "American-Samoa", Location: "American Samoa", CountryCode: "", Flag: "🇦🇸"},
			{Key: "Andorra", Location: "Andorra", CountryCode: "AD", Flag: "🇦🇩"},
			{Key: "Angola", Location: "Angola", CountryCode: "AO", Flag: "🇦🇴"},
			{Key: "Anguilla", Location: "Anguilla", CountryCode: "AI", Flag: "🇦🇮"},
			{Key: "Antigua-and-Barbuda", Location: "Antigua And Barbuda", CountryCode: "AG", Flag: "🇦🇬"},
			{Key: "Argentina", Location: "Argentina", CountryCode: "AR", Flag: "🇦🇷"},
			{Key: "Armenia", Location: "Armenia", CountryCode: "AM", Flag: "🇦🇲"},
			{Key: "Aruba", Location: "Aruba", CountryCode: "AW", Flag: "🇦🇼"},
			{Key: "Austria", Location: "Austria", CountryCode: "AT", Flag: "🇦🇹"},
			{Key: "Azerbaijan", Location: "Azerbaijan", CountryCode: "AZ", Flag: "🇦🇿"},
			{Key: "Bahrain", Location: "Bahrain", CountryCode: "BH", Flag: "🇧🇭"},
			{Key: "Bangladesh", Location: "Bangladesh", CountryCode: "BD", Flag: "🇧🇩"},
			{Key: "Belarus", Location: "Belarus", CountryCode: "BY", Flag: "🇧🇾"},
			{Key: "Belize", Location: "Belize", CountryCode: "BZ", Flag: "🇧🇿"},
			{Key: "Benin", Location: "Benin", CountryCode: "BJ", Flag: "🇧🇯"},
			{Key: "Bermuda", Location: "Bermuda", CountryCode: "BM", Flag: "🇧🇲"},
			{Key: "Bhutan", Location: "Bhutan", CountryCode: "BT", Flag: "🇧🇹"},
			{Key: "Bolivia", Location: "Bolivia", CountryCode: "BO", Flag: "🇧🇴"},
			{Key: "Bosnia-and-Herzegovina", Location: "Bosnia And Herzegovina", CountryCode: "BA", Flag: "🇧🇦"},
			{Key: "Botswana", Location: "Botswana", CountryCode: "BW", Flag: "🇧🇼"},
			{Key: "Bouvet-Island", Location: "Bouvet Island", CountryCode: "BV", Flag: "🇧🇻"},
			{Key: "British-Indian-Ocean-Territory", Location: "British Indian Ocean Territory", CountryCode: "IO", Flag: "🇮🇴"},
			{Key: "Brunei", Location: "Brunei", CountryCode: "BN", Flag: "🇧🇳"},
			{Key: "Bulgaria", Location: "Bulgaria", CountryCode: "BG", Flag: "🇧🇬"},
			{Key: "Burkina-Faso", Location: "Burkina Faso", CountryCode: "BF", Flag: "🇧🇫"},
			{Key: "Burundi", Location: "Burundi", CountryCode: "BI", Flag: "🇧🇮"},
			{Key: "Cambodia", Location: "Cambodia", CountryCode: "KH", Flag: "🇰🇭"},
			{Key: "Cameroon", Location: "Cameroon", CountryCode: "CM", Flag: "🇨🇲"},
			{Key: "Cabo-Verde", Location: "Cabo Verde", CountryCode: "CV", Flag: "🇨🇻"},
			{Key: "Caribbean-Netherlands", Location: "Caribbean Netherlands", CountryCode: "", Flag: "🇧🇶"},
			{Key: "Cayman-Islands", Location: "Cayman Islands", CountryCode: "KY", Flag: "🇰🇾"},
			{Key: "CAR", Location: "CAR", CountryCode: "CF", Flag: "🇨🇫"},
			{Key: "Chad", Location: "Chad", CountryCode: "TD", Flag: "🇹🇩"},
			{Key: "Christmas-Island", Location: "Christmas Island", CountryCode: "CX", Flag: "🇨🇽"},
			{Key: "Cocos-(Keeling)-Islands", Location: "Cocos (Keeling) Islands", CountryCode: "CC", Flag: "🇨🇨"},
			{Key: "Colombia", Location: "Colombia", CountryCode: "CO", Flag: "🇨🇴"},
			{Key: "Comoros", Location: "Comoros", CountryCode: "KM", Flag: "🇰🇲"},
			{Key: "DRC", Location: "DRC", CountryCode: "CD", Flag: "🇨🇬"},
			{Key: "Congo", Location: "Congo", CountryCode: "CG", Flag: "🇨🇩"},
			{Key: "Cook-Islands", Location: "Cook Islands", CountryCode: "CK", Flag: "🇨🇰"},
			{Key: "Costa-Rica", Location: "Costa Rica", CountryCode: "CR", Flag: "🇨🇷"},
			{Key: "Ivory-Coast", Location: "Ivory Coast", CountryCode: "CI", Flag: "🇨🇮"},
			{Key: "Croatia", Location: "Croatia", CountryCode: "HR", Flag: "🇭🇷"},
			{Key: "Cuba", Location: "Cuba", CountryCode: "CU", Flag: "🇨🇺"},
			{Key: "Curaçao", Location: "Curaçao", CountryCode: "CW", Flag: "🇨🇼"},
			{Key: "Cyprus", Location: "Cyprus", CountryCode: "CY", Flag: "🇨🇾"},
			{Key: "Czechia", Location: "Czechia", CountryCode: "CZ", Flag: "🇨🇿"},
			{Key: "Denmark", Location: "Denmark", CountryCode: "DK", Flag: "🇩🇰"},
			{Key: "Djibouti", Location: "Djibouti", CountryCode: "DJ", Flag: "🇩🇯"},
			{Key: "Dominica", Location: "Dominica", CountryCode: "DM", Flag: "🇩🇲"},
			{Key: "Dominican-Republic", Location: "Dominican Republic", CountryCode: "DO", Flag: "🇩🇴"},
			{Key: "Ecuador", Location: "Ecuador", CountryCode: "EC", Flag: "🇪🇨"},
			{Key: "Egypt", Location: "Egypt", CountryCode: "EG", Flag: "🇪🇬"},
			{Key: "El-Salvador", Location: "El Salvador", CountryCode: "SV", Flag: "🇸🇻"},
			{Key: "󠁥󠁮󠁧󠁿England", Location: "󠁥󠁮󠁧󠁿England", CountryCode: "", Flag: "🏴󠁧󠁢"},
			{Key: "Equatorial-Guinea", Location: "Equatorial Guinea", CountryCode: "", Flag: "🇬🇶"},
			{Key: "Eritrea", Location: "Eritrea", CountryCode: "ER", Flag: "🇪🇷"},
			{Key: "Estonia", Location: "Estonia", CountryCode: "EE", Flag: "🇪🇪"},
			{Key: "Eswatini", Location: "Eswatini", CountryCode: "SZ", Flag: "🇸🇿"},
			{Key: "Ethiopia", Location: "Ethiopia", CountryCode: "ET", Flag: "🇪🇹"},
			{Key: "Falkland-Islands", Location: "Falkland Islands", CountryCode: "FK", Flag: "🇫🇰"},
			{Key: "Faeroe-Islands", Location: "Faeroe Islands", CountryCode: "FO", Flag: "🇫🇴"},
			{Key: "Fiji", Location: "Fiji", CountryCode: "FJ", Flag: "🇫🇯"},
			{Key: "Finland", Location: "Finland", CountryCode: "FI", Flag: "🇫🇮"},
			{Key: "French-Guiana", Location: "French Guiana", CountryCode: "GF", Flag: "🇬🇫"},
			{Key: "French-Polynesia", Location: "French Polynesia", CountryCode: "PF", Flag: "🇵🇫"},
			{Key: "French-Southern-and-Antarctic-Lands", Location: "French Southern And Antarctic Lands", CountryCode: "TF", Flag: "🇹🇫"},
			{Key: "Gabon", Location: "Gabon", CountryCode: "GA", Flag: "🇬🇦"},
			{Key: "Gambia", Location: "Gambia", CountryCode: "GM", Flag: "🇬🇲"},
			{Key: "Georgia", Location: "Georgia", CountryCode: "GE", Flag: "🇬🇪"},
			{Key: "Ghana", Location: "Ghana", CountryCode: "GH", Flag: "🇬🇭"},
			{Key: "Gibraltar", Location: "Gibraltar", CountryCode: "GI", Flag: "🇬🇮"},
			{Key: "Greece", Location: "Greece", CountryCode: "GR", Flag: "🇬🇷"},
			{Key: "Greenland", Location: "Greenland", CountryCode: "GL", Flag: "🇬🇱"},
			{Key: "Grenada", Location: "Grenada", CountryCode: "GD", Flag: "🇬🇩"},
			{Key: "Guadeloupe", Location: "Guadeloupe", CountryCode: "GP", Flag: "🇬🇵"},
			{Key: "Guam", Location: "Guam", CountryCode: "GU", Flag: "🇬🇺"},
			{Key: "Guatemala", Location: "Guatemala", CountryCode: "GT", Flag: "🇬🇹"},
			{Key: "Guernsey", Location: "Guernsey", CountryCode: "GG", Flag: "🇬🇬"},
			{Key: "Guinea", Location: "Guinea", CountryCode: "GN", Flag: "🇬🇳"},
			{Key: "Guinea-Bissau", Location: "Guinea Bissau", CountryCode: "GW", Flag: "🇬🇼"},
			{Key: "Guyana", Location: "Guyana", CountryCode: "GY", Flag: "🇬🇾"},
			{Key: "Haiti", Location: "Haiti", CountryCode: "HT", Flag: "🇭🇹"},
			{Key: "Heard-Island-and-McDonald-Islands", Location: "Heard Island And McDonald Islands", CountryCode: "HM", Flag: "🇭🇲"},
			{Key: "Honduras", Location: "Honduras", CountryCode: "HN", Flag: "🇭🇳"},
			{Key: "Hong-Kong", Location: "Hong Kong", CountryCode: "HK", Flag: "🇭🇰"},
			{Key: "Hungary", Location: "Hungary", CountryCode: "HU", Flag: "🇭🇺"},
			{Key: "Iceland", Location: "Iceland", CountryCode: "IS", Flag: "🇮🇸"},
			{Key: "Indonesia", Location: "Indonesia", CountryCode: "ID", Flag: "🇮🇩"},
			{Key: "Iraq", Location: "Iraq", CountryCode: "IQ", Flag: "🇮🇶"},
			{Key: "Ireland", Location: "Ireland", CountryCode: "IE", Flag: "🇮🇪"},
			{Key: "Isle-of-Man", Location: "Isle Of Man", CountryCode: "IM", Flag: "🇮🇲"},
			{Key: "Israel", Location: "Israel", CountryCode: "IL", Flag: "🇮🇱"},
			{Key: "Jamaica", Location: "Jamaica", CountryCode: "JM", Flag: "🇯🇲"},
			{Key: "Japan", Location: "Japan", CountryCode: "JP", Flag: "🇯🇵"},
			{Key: "Channel-Islands", Location: "Channel Islands", CountryCode: "JE", Flag: "🇯🇪"},
			{Key: "Jordan", Location: "Jordan", CountryCode: "JO", Flag: "🇯🇴"},
			{Key: "Kazakhstan", Location: "Kazakhstan", CountryCode: "KZ", Flag: "🇰🇿"},
			{Key: "Kenya", Location: "Kenya", CountryCode: "KE", Flag: "🇰🇪"},
			{Key: "Kiribati", Location: "Kiribati", CountryCode: "KI", Flag: "🇰🇮"},
			{Key: "N-Korea", Location: "N Korea", CountryCode: "KP", Flag: "🇰🇵"},
			{Key: "S-Korea", Location: "S Korea", CountryCode: "KR", Flag: "🇰🇷"},
			{Key: "Kosovo", Location: "Kosovo", CountryCode: "", Flag: "🇽🇰"},
			{Key: "Kuwait", Location: "Kuwait", CountryCode: "KW", Flag: "🇰🇼"},
			{Key: "Kyrgyzstan", Location: "Kyrgyzstan", CountryCode: "KG", Flag: "🇰🇬"},
			{Key: "Laos", Location: "Laos", CountryCode: "LA", Flag: "🇱🇦"},
			{Key: "Latvia", Location: "Latvia", CountryCode: "LV", Flag: "🇱🇻"},
			{Key: "Lebanon", Location: "Lebanon", CountryCode: "LB", Flag: "🇱🇧"},
			{Key: "Lesotho", Location: "Lesotho", CountryCode: "LS", Flag: "🇱🇸"},
			{Key: "Liberia", Location: "Liberia", CountryCode: "LR", Flag: "🇱🇷"},
			{Key: "Libya", Location: "Libya", CountryCode: "LY", Flag: "🇱🇾"},
			{Key: "Liechtenstein", Location: "Liechtenstein", CountryCode: "LI", Flag: "🇱🇮"},
			{Key: "Lithuania", Location: "Lithuania", CountryCode: "LT", Flag: "🇱🇹"},
			{Key: "Luxembourg", Location: "Luxembourg", CountryCode: "LU", Flag: "🇱🇺"},
			{Key: "Macao", Location: "Macao", CountryCode: "MO", Flag: "🇲🇴"},
			{Key: "Madagascar", Location: "Madagascar", CountryCode: "MG", Flag: "🇲🇬"},
			{Key: "Malawi", Location: "Malawi", CountryCode: "MW", Flag: "🇲🇼"},
			{Key: "Malaysia", Location: "Malaysia", CountryCode: "MY", Flag: "🇲🇾"},
			{Key: "Maldives", Location: "Maldives", CountryCode: "MV", Flag: "🇲🇻"},
			{Key: "Mali", Location: "Mali", CountryCode: "ML", Flag: "🇲🇱"},
			{Key: "Malta", Location: "Malta", CountryCode: "MT", Flag: "🇲🇹"},
			{Key: "Marshall-Islands", Location: "Marshall Islands", CountryCode: "MH", Flag: "🇲🇭"},
			{Key: "Martinique", Location: "Martinique", CountryCode: "MQ", Flag: "🇲🇶"},
			{Key: "Mauritania", Location: "Mauritania", CountryCode: "MR", Flag: "🇲🇷"},
			{Key: "Mauritius", Location: "Mauritius", CountryCode: "MU", Flag: "🇲🇺"},
			{Key: "Mayotte", Location: "Mayotte", CountryCode: "YT", Flag: "🇾🇹"},
			{Key: "Micronesia", Location: "Micronesia", CountryCode: "FM", Flag: "🇫🇲"},
			{Key: "Moldova", Location: "Moldova", CountryCode: "MD", Flag: "🇲🇩"},
			{Key: "Monaco", Location: "Monaco", CountryCode: "MC", Flag: "🇲🇨"},
			{Key: "Mongolia", Location: "Mongolia", CountryCode: "MN", Flag: "🇲🇳"},
			{Key: "Montenegro", Location: "Montenegro", CountryCode: "ME", Flag: "🇲🇪"},
			{Key: "Montserrat", Location: "Montserrat", CountryCode: "MS", Flag: "🇲🇸"},
			{Key: "Morocco", Location: "Morocco", CountryCode: "MA", Flag: "🇲🇦"},
			{Key: "Mozambique", Location: "Mozambique", CountryCode: "MZ", Flag: "🇲🇿"},
			{Key: "Myanmar", Location: "Myanmar", CountryCode: "MM", Flag: "🇲🇲"},
			{Key: "Namibia", Location: "Namibia", CountryCode: "NA", Flag: "🇳🇦"},
			{Key: "Nauru", Location: "Nauru", CountryCode: "NR", Flag: "🇳🇷"},
			{Key: "Nepal", Location: "Nepal", CountryCode: "NP", Flag: "🇳🇵"},
			{Key: "Netherlands", Location: "Netherlands", CountryCode: "NL", Flag: "🇳🇱"},
			{Key: "New-Caledonia", Location: "New Caledonia", CountryCode: "NC", Flag: "🇳🇨"},
			{Key: "Nicaragua", Location: "Nicaragua", CountryCode: "NI", Flag: "🇳🇮"},
			{Key: "Niger", Location: "Niger", CountryCode: "NE", Flag: "🇳🇪"},
			{Key: "Nigeria", Location: "Nigeria", CountryCode: "NG", Flag: "🇳🇬"},
			{Key: "Niue", Location: "Niue", CountryCode: "NU", Flag: "🇳🇺"},
			{Key: "Norfolk-Island", Location: "Norfolk Island", CountryCode: "NF", Flag: "🇳🇫"},
			{Key: "North-Macedonia", Location: "North Macedonia", CountryCode: "MK", Flag: "🇲🇰"},
			{Key: "Northern-Mariana-Islands", Location: "Northern Mariana Islands", CountryCode: "MP", Flag: "🇲🇵"},
			{Key: "Norway", Location: "Norway", CountryCode: "NO", Flag: "🇳🇴"},
			{Key: "Oman", Location: "Oman", CountryCode: "OM", Flag: "🇴🇲"},
			{Key: "Pakistan", Location: "Pakistan", CountryCode: "PK", Flag: "🇵🇰"},
			{Key: "Palau", Location: "Palau", CountryCode: "PW", Flag: "🇵🇼"},
			{Key: "Palestine", Location: "Palestine", CountryCode: "PS", Flag: "🇵🇸"},
			{Key: "Panama", Location: "Panama", CountryCode: "PA", Flag: "🇵🇦"},
			{Key: "Papua-New-Guinea", Location: "Papua New Guinea", CountryCode: "PG", Flag: "🇵🇬"},
			{Key: "Paraguay", Location: "Paraguay", CountryCode: "PY", Flag: "🇵🇾"},
			{Key: "Philippines", Location: "Philippines", CountryCode: "PH", Flag: "🇵🇭"},
			{Key: "Pitcairn-Islands", Location: "Pitcairn Islands", CountryCode: "PN", Flag: "🇵🇳"},
			{Key: "Portugal", Location: "Portugal", CountryCode: "PT", Flag: "🇵🇹"},
			{Key: "Puerto-Rico", Location: "Puerto Rico", CountryCode: "PR", Flag: "🇵🇷"},
			{Key: "Qatar", Location: "Qatar", CountryCode: "QA", Flag: "🇶🇦"},
			{Key: "Réunion", Location: "Réunion", CountryCode: "RE", Flag: "🇷🇪"},
			{Key: "Romania", Location: "Romania", CountryCode: "RO", Flag: "🇷🇴"},
			{Key: "Rwanda", Location: "Rwanda", CountryCode: "RW", Flag: "🇷🇼"},
			{Key: "St-Barth", Location: "St Barth", CountryCode: "BL", Flag: "🇧🇱"},
			{Key: "Saint-Helena", Location: "Saint Helena", CountryCode: "SH", Flag: "🇸🇭"},
			{Key: "Saint-Kitts-and-Nevis", Location: "Saint Kitts And Nevis", CountryCode: "KN", Flag: "🇰🇳"},
			{Key: "Saint-Lucia", Location: "Saint Lucia", CountryCode: "LC", Flag: "🇱🇨"},
			{Key: "Saint-Martin", Location: "Saint Martin", CountryCode: "MF", Flag: "🇲🇫"},
			{Key: "Saint-Pierre-Miquelon", Location: "Saint Pierre Miquelon", CountryCode: "PM", Flag: "🇵🇲"},
			{Key: "St-Vincent-Grenadines", Location: "St Vincent Grenadines", CountryCode: "VC", Flag: "🇻🇨"},
			{Key: "Samoa", Location: "Samoa", CountryCode: "WS", Flag: "🇼🇸"},
			{Key: "San-Marino", Location: "San Marino", CountryCode: "SM", Flag: "🇸🇲"},
			{Key: "Sao-Tome-and-Principe", Location: "Sao Tome And Principe", CountryCode: "ST", Flag: "🇸🇹"},
			{Key: "󠁳󠁣󠁴󠁿Scotland", Location: "󠁳󠁣󠁴󠁿Scotland", CountryCode: "", Flag: "🏴󠁧󠁢"},
			{Key: "Senegal", Location: "Senegal", CountryCode: "SN", Flag: "🇸🇳"},
			{Key: "Serbia", Location: "Serbia", CountryCode: "RS", Flag: "🇷🇸"},
			{Key: "Seychelles", Location: "Seychelles", CountryCode: "SC", Flag: "🇸🇨"},
			{Key: "Sierra-Leone", Location: "Sierra Leone", CountryCode: "SL", Flag: "🇸🇱"},
			{Key: "Singapore", Location: "Singapore", CountryCode: "SG", Flag: "🇸🇬"},
			{Key: "Sint-Maarten", Location: "Sint Maarten", CountryCode: "", Flag: "🇸🇽"},
			{Key: "Slovakia", Location: "Slovakia", CountryCode: "SK", Flag: "🇸🇰"},
			{Key: "Slovenia", Location: "Slovenia", CountryCode: "SI", Flag: "🇸🇮"},
			{Key: "Solomon-Islands", Location: "Solomon Islands", CountryCode: "SB", Flag: "🇸🇧"},
			{Key: "Somalia", Location: "Somalia", CountryCode: "SO", Flag: "🇸🇴"},
			{Key: "South-Africa", Location: "South Africa", CountryCode: "ZA", Flag: "🇿🇦"},
			{Key: "South-Georgia", Location: "South Georgia", CountryCode: "GS", Flag: "🇬🇸"},
			{Key: "South-Sudan", Location: "South Sudan", CountryCode: "SS", Flag: "🇸🇸"},
			{Key: "Sri-Lanka", Location: "Sri Lanka", CountryCode: "LK", Flag: "🇱🇰"},
			{Key: "Sudan", Location: "Sudan", CountryCode: "SD", Flag: "🇸🇩"},
			{Key: "Suriname", Location: "Suriname", CountryCode: "SR", Flag: "🇸🇷"},
			{Key: "Svalbard-and-Jan-Mayen", Location: "Svalbard And Jan Mayen", CountryCode: "SJ", Flag: "🇸🇯"},
			{Key: "Sweden", Location: "Sweden", CountryCode: "SE", Flag: "🇸🇪"},
			{Key: "Switzerland", Location: "Switzerland", CountryCode: "CH", Flag: "🇨🇭"},
			{Key: "Syria", Location: "Syria", CountryCode: "SY", Flag: "🇸🇾"},
			{Key: "Taiwan", Location: "Taiwan", CountryCode: "TW", Flag: "🇹🇼"},
			{Key: "Tajikistan", Location: "Tajikistan", CountryCode: "TJ", Flag: "🇹🇯"},
			{Key: "Tanzania", Location: "Tanzania", CountryCode: "TZ", Flag: "🇹🇿"},
			{Key: "Thailand", Location: "Thailand", CountryCode: "TH", Flag: "🇹🇭"},
			{Key: "Timor-Leste", Location: "Timor Leste", CountryCode: "TL", Flag: "🇹🇱"},
			{Key: "Togo", Location: "Togo", CountryCode: "TG", Flag: "🇹🇬"},
			{Key: "Tokelau", Location: "Tokelau", CountryCode: "TK", Flag: "🇹🇰"},
			{Key: "Tonga", Location: "Tonga", CountryCode: "TO", Flag: "🇹🇴"},
			{Key: "Trinidad-and-Tobago", Location: "Trinidad And Tobago", CountryCode: "TT", Flag: "🇹🇹"},
			{Key: "Tunisia", Location: "Tunisia", CountryCode: "TN", Flag: "🇹🇳"},
			{Key: "Turkmenistan", Location: "Turkmenistan", CountryCode: "TM", Flag: "🇹🇲"},
			{Key: "Turks-and-Caicos", Location: "Turks And Caicos", CountryCode: "TC", Flag: "🇹🇨"},
			{Key: "Tuvalu", Location: "Tuvalu", CountryCode: "TV", Flag: "🇹🇻"},
			{Key: "Uganda", Location: "Uganda", CountryCode: "UG", Flag: "🇺🇬"},
			{Key: "Ukraine", Location: "Ukraine", CountryCode: "UA", Flag: "🇺🇦"},
			{Key: "UAE", Location: "UAE", CountryCode: "AE", Flag: "🇦🇪"},
			{Key: "United-States-Minor-Outlying-Islands", Location: "United States Minor Outlying Islands", CountryCode: "UM", Flag: "🇺🇲"},
			{Key: "Uruguay", Location: "Uruguay", CountryCode: "UY", Flag: "🇺🇾"},
			{Key: "Uzbekistan", Location: "Uzbekistan", CountryCode: "UZ", Flag: "🇺🇿"},
			{Key: "Vanuatu", Location: "Vanuatu", CountryCode: "VU", Flag: "🇻🇺"},
			{Key: "Vatican-City", Location: "Vatican City", CountryCode: "VA", Flag: "🇻🇦"},
			{Key: "Venezuela", Location: "Venezuela", CountryCode: "VE", Flag: "🇻🇪"},
			{Key: "Vietnam", Location: "Vietnam", CountryCode: "VN", Flag: "🇻🇳"},
			{Key: "British-Virgin-Islands", Location: "British Virgin Islands", CountryCode: "VG", Flag: "🇻🇬"},
			{Key: "US-Virgin-Islands", Location: "US Virgin Islands", CountryCode: "VI", Flag: "🇻🇮"},
			{Key: "󠁷󠁬󠁳󠁿Wales", Location: "󠁷󠁬󠁳󠁿Wales", CountryCode: "", Flag: "🏴󠁧󠁢"},
			{Key: "Wallis-and-Futuna", Location: "Wallis And Futuna", CountryCode: "WF", Flag: "🇼🇫"},
			{Key: "Western-Sahara", Location: "Western Sahara", CountryCode: "EH", Flag: "🇪🇭"},
			{Key: "Yemen", Location: "Yemen", CountryCode: "YE", Flag: "🇾🇪"},
			{Key: "Zambia", Location: "Zambia", CountryCode: "ZM", Flag: "🇿🇲"},
			{Key: "Zimbabwe", Location: "Zimbabwe", CountryCode: "ZW", Flag: "🇿🇼"},
		},
	}
}
