apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-deployment
  labels:
    app: go-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-web
  template:
    metadata:
      labels:
        app: go-web
    spec:
      serviceAccountName: go-web-service-account
      containers:
      - name: go-web-pod
        image: colinschofield/go-web:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: go-web-service
spec:
  type: LoadBalancer
  selector:
    app: go-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080        
