apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-deployment
  labels:
    app: go-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-web
  template:
    metadata:
      labels:
        app: go-web
    spec:
      serviceAccountName: go-web-service-account
      containers:
      - name: go-web-pod
        image: colinschofield/go-web:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: API_VERSION      
          value: /api/1.0        
        - name: EXCLUDE_REGIONS  
          value: All|Asia|Oceania|Europe|North-America|Africa|South-America|Diamond-Princess-|Cura&ccedil;ao|R&eacute;union|MS-Zaandam-|Diamond-Princess|guam|Cook Islands|Palau|Nauru|Kiribati|Niue|Tuvalu|Tonga|Micronesia|DPRK
        - name: SUMMARY_END_POINT
          value: https://covid-193.p.rapidapi.com/statistics
        - name: SUMMARY_HOST     
          value: covid-193.p.rapidapi.com
        - name: SUMMARY_KEY      
          value: cb1f09fd7dmsh35f7dd8afd27dfdp191e0cjsnca765ccf022a
        - name: HISTORY_END_POINT
          value: https://vaccovid-coronavirus-vaccine-and-treatment-tracker.p.rapidapi.com/api/covid-ovid-data/sixmonth/%s
        - name: HISTORY_HOST     
          value: vaccovid-coronavirus-vaccine-and-treatment-tracker.p.rapidapi.com
        - name: HISTORY_KEY      
          value: cb1f09fd7dmsh35f7dd8afd27dfdp191e0cjsnca765ccf022a
        - name: AWS_REGION       
          value: ap-southeast-2
        - name: DB_TABLE_NAME    
          value: User
---
apiVersion: v1
kind: Service
metadata:
  name: go-web-service
spec:
  type: LoadBalancer
  selector:
    app: go-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080        
