name: CI/CD with AWS EKS 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Build, tag and push to Docker Hub
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }} 
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name authenticator
      uses: woofenator/action-aws-iam-authenticator@master
    - run: aws-iam-authenticator version

    - name: Build and push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: src
        push: true
        tags:  colinschofield/go-web:latest, colinschofield/go-web:${{ github.run_number }}

    - name: Perform a K8s rolling update (loading the new image snapshot via imagePullPolicy of 'Always') 
      uses: steebchen/kubectl@v2.0.0
      with:
        config: ${{ secrets.KUBE_CONFIG }}
        version: v1.21.0
        command: get pods