name: CI/CD with AWS EKS 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Build, tag and push to Docker Hub
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }} 
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: src
        push: true
        tags:  colinschofield/go-web:latest, colinschofield/go-web:${{ github.run_number }}

    - name: Perform a K8s rolling update (loading the new image snapshot via imagePullPolicy of 'Always')
      uses: Jberlinsky/kubernetes-action@master
      env:
        aws-access-key-id: ${{ secrets.DOCKER_HUB_USERNAME }}
        aws-secret-access-key: ${{ secrets['DEV_AWS_SECRET_ACCESS_KEY'] }}
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
      with:
        args: get pods